In [1]:
from google.colab import files
import pandas as pd
import glob

# Upload all 7 CSV files
uploaded = files.upload()

# Read and merge all CSVs
dfs = []
for file in glob.glob("*.csv"):
    dfs.append(pd.read_csv(file))

merged_df = pd.concat(dfs, ignore_index=True)

print("Merged Shape:", merged_df.shape)
merged_df.head()

Saving 1.csv to 1.csv
Saving 2.csv to 2.csv
Saving 3.csv to 3.csv
Saving 4.csv to 4.csv
Saving 5.csv to 5.csv
Saving 6.csv to 6.csv
Saving 7.csv to 7.csv
Merged Shape: (19716, 126)

,,Time,Time.1,Place,Place.1,Place.2,Place.3,Place.4,Place.5,Place.6,...,Events.4,Events.5,Assessments,Assessments.1,Report 1,Report 1.1,Report 2,Report 2.1,Report 1.2,Unnamed: 125
0,ACN,Date,Local Time Of Day,Locale Reference,State Reference,Relative Position.Angle.Radial,Relative Position.Distance.Nautical Miles,Altitude.AGL.Single Value,Altitude.MSL.Single Value,Latitude / Longitude (UAS),...,When Detected,Result,Contributing Factors / Situations,Primary Problem,Narrative,Callback,Narrative,Callback,Synopsis,NaN
1,2068164,202401,1201-1800,ZZZ.Airport,US,NaN,NaN,0,NaN,NaN,...,NaN,Flight Crew Rejected Takeoff; Flight Crew Took...,Procedure; Human Factors,Human Factors,Was told to line up and wait runway XXR at int...,NaN,Crew was preparing for departure to ZZZ1. The ...,NaN,DA-7X flight crew rejected a takeoff due to an...,NaN
2,2068412,202401,0601-1200,SKX.Airport,NM,NaN,NaN,0,NaN,NaN,...,Taxi,General None Reported / Taken,Human Factors; Procedure,Human Factors,A large corporate aircraft taxied with in 5-8 ...,NaN,NaN,NaN,Ground observer reported a critical ground con...,NaN
3,2068417,202401,1201-1800,LCCC.ARTCC,FO,NaN,NaN,NaN,38000,NaN,...,In-flight,Flight Crew Overcame Equipment Problem,ATC Equipment / Nav Facility / Buildings; Airc...,ATC Equipment / Nav Facility / Buildings,GPS Spoofing. Enroute today from ZZZ to SOF; w...,NaN,NaN,NaN,Air carrier pilot reported GPS spoofing at cru...,NaN
4,2068537,202401,1201-1800,MCO.TRACON,FL,090,2,NaN,2500,NaN,...,In-flight,Flight Crew Took Evasive Action,Human Factors; Procedure,Human Factors,Practicing simulated arcs with instrument stud...,NaN,NaN,NaN,General aviation Instructor reported a near mi...,NaN

In [2]:
# NASA exports usually have the first row as actual headers

new_header = merged_df.iloc[0]

merged_df = merged_df[1:]
merged_df.columns = new_header
merged_df.reset_index(drop=True, inplace=True)

print("Columns:\n")
for col in merged_df.columns:
    print(col)

print("\nDataset Shape:", merged_df.shape)

merged_df.head()

Columns:

ACN
Date
Local Time Of Day
Locale Reference
State Reference
Relative Position.Angle.Radial
Relative Position.Distance.Nautical Miles
Altitude.AGL.Single Value
Altitude.MSL.Single Value
Latitude / Longitude (UAS)
Flight Conditions
Weather Elements / Visibility
Work Environment Factor
Light
Ceiling
RVR.Single Value
ATC / Advisory
Aircraft Operator
Make Model Name
Aircraft Zone
Crew Size
Operating Under FAR Part
Flight Plan
Mission
Nav In Use
Flight Phase
Route In Use
Airspace
Maintenance Status.Maintenance Deferred
Maintenance Status.Records Complete
Maintenance Status.Released For Service
Maintenance Status.Required / Correct Doc On Board
Maintenance Status.Maintenance Type
Maintenance Status.Maintenance Items Involved
Cabin Lighting
Number Of Seats.Number
Passengers On Board.Number
Crew Size Flight Attendant.Number Of Crew
Airspace Authorization Provider (UAS)
Operating Under Waivers / Exemptions / Authorizations (UAS)
Waivers / Exemptions / Authorizations (UAS)
Airworthiness Certification (UAS)
Weight Category (UAS)
Configuration (UAS)
Flight Operated As (UAS)
Flight Operated with Visual Observer (UAS)
Control Mode (UAS)
Flying In / Near / Over (UAS)
Passenger Capable (UAS)
Type (UAS)
Number of UAS Being Controlled (UAS)
Aircraft Component
Manufacturer
Aircraft Reference
Problem
ATC / Advisory
Aircraft Operator
Make Model Name
Aircraft Zone
Crew Size
Operating Under FAR Part
Flight Plan
Mission
Nav In Use
Flight Phase
Route In Use
Airspace
Maintenance Status.Maintenance Deferred
Maintenance Status.Records Complete
Maintenance Status.Released For Service
Maintenance Status.Required / Correct Doc On Board
Maintenance Status.Maintenance Type
Maintenance Status.Maintenance Items Involved
Cabin Lighting
Number Of Seats.Number
Passengers On Board.Number
Crew Size Flight Attendant.Number Of Crew
Airspace Authorization Provider (UAS)
Operating Under Waivers / Exemptions / Authorizations (UAS)
Waivers / Exemptions / Authorizations (UAS)
Airworthiness Certification (UAS)
Weight Category (UAS)
Configuration (UAS)
Flight Operated As (UAS)
Flight Operated with Visual Observer (UAS)
Control Mode (UAS)
Flying In / Near / Over (UAS)
Passenger Capable (UAS)
Type (UAS)
Number of UAS Being Controlled (UAS)
Location Of Person
Location In Aircraft
Reporter Organization
Function
Qualification
Experience
Cabin Activity
Human Factors
Communication Breakdown
UAS Communication Breakdown
ASRS Report Number.Accession Number
Location Of Person
Location In Aircraft
Reporter Organization
Function
Qualification
Experience
Cabin Activity
Human Factors
Communication Breakdown
UAS Communication Breakdown
ASRS Report Number.Accession Number
Anomaly
Miss Distance
Were Passengers Involved In Event
Detector
When Detected
Result
Contributing Factors / Situations
Primary Problem
Narrative
Callback
Narrative
Callback
Synopsis
nan

Dataset Shape: (19715, 126)

,ACN,Date,Local Time Of Day,Locale Reference,State Reference,Relative Position.Angle.Radial,Relative Position.Distance.Nautical Miles,Altitude.AGL.Single Value,Altitude.MSL.Single Value,Latitude / Longitude (UAS),...,When Detected,Result,Contributing Factors / Situations,Primary Problem,Narrative,Callback,Narrative,Callback,Synopsis,NaN
0,2068164,202401,1201-1800,ZZZ.Airport,US,NaN,NaN,0,NaN,NaN,...,NaN,Flight Crew Rejected Takeoff; Flight Crew Took...,Procedure; Human Factors,Human Factors,Was told to line up and wait runway XXR at int...,NaN,Crew was preparing for departure to ZZZ1. The ...,NaN,DA-7X flight crew rejected a takeoff due to an...,NaN
1,2068412,202401,0601-1200,SKX.Airport,NM,NaN,NaN,0,NaN,NaN,...,Taxi,General None Reported / Taken,Human Factors; Procedure,Human Factors,A large corporate aircraft taxied with in 5-8 ...,NaN,NaN,NaN,Ground observer reported a critical ground con...,NaN
2,2068417,202401,1201-1800,LCCC.ARTCC,FO,NaN,NaN,NaN,38000,NaN,...,In-flight,Flight Crew Overcame Equipment Problem,ATC Equipment / Nav Facility / Buildings; Airc...,ATC Equipment / Nav Facility / Buildings,GPS Spoofing. Enroute today from ZZZ to SOF; w...,NaN,NaN,NaN,Air carrier pilot reported GPS spoofing at cru...,NaN
3,2068537,202401,1201-1800,MCO.TRACON,FL,090,2,NaN,2500,NaN,...,In-flight,Flight Crew Took Evasive Action,Human Factors; Procedure,Human Factors,Practicing simulated arcs with instrument stud...,NaN,NaN,NaN,General aviation Instructor reported a near mi...,NaN
4,2068539,202401,1201-1800,ZJX.ARTCC,FL,NaN,NaN,NaN,7500,NaN,...,In-flight,Flight Crew Requested ATC Assistance / Clarifi...,Chart Or Publication; Procedure; Airspace Stru...,Procedure,I was enroute southeast bound on T208 VFR; in ...,NaN,NaN,NaN,Experimental aircraft pilot operating in ZMA a...,NaN

In [3]:
for i, col in enumerate(merged_df.columns):
    if str(col).strip().lower() == "narrative":
        print(i, col)

120 Narrative
122 Narrative

In [4]:
merged_df.iloc[:5, [118,119,120,121,122]]

,Contributing Factors / Situations,Primary Problem,Narrative,Callback,Narrative
0,Procedure; Human Factors,Human Factors,Was told to line up and wait runway XXR at int...,NaN,Crew was preparing for departure to ZZZ1. The ...
1,Human Factors; Procedure,Human Factors,A large corporate aircraft taxied with in 5-8 ...,NaN,NaN
2,ATC Equipment / Nav Facility / Buildings; Airc...,ATC Equipment / Nav Facility / Buildings,GPS Spoofing. Enroute today from ZZZ to SOF; w...,NaN,NaN
3,Human Factors; Procedure,Human Factors,Practicing simulated arcs with instrument stud...,NaN,NaN
4,Chart Or Publication; Procedure; Airspace Stru...,Procedure,I was enroute southeast bound on T208 VFR; in ...,NaN,NaN

In [5]:
import pandas as pd

# Rename duplicate narrative columns
cols = list(merged_df.columns)

narrative_count = 0
new_cols = []

for col in cols:
    if col == "Narrative":
        narrative_count += 1
        new_cols.append(f"Narrative_{narrative_count}")
    else:
        new_cols.append(col)

merged_df.columns = new_cols

# Create combined narrative
merged_df["full_narrative"] = (
    merged_df["Narrative_1"].fillna("") +
    " " +
    merged_df["Narrative_2"].fillna("")
)

# Keep only useful columns
clean_df = merged_df[
    [
        "ACN",
        "Date",
        "Primary Problem",
        "Contributing Factors / Situations",
        "Result",
        "Synopsis",
        "full_narrative"
    ]
]

# Remove empty reports
clean_df = clean_df.dropna(subset=["full_narrative"])

clean_df = clean_df[
    clean_df["full_narrative"].str.strip().str.len() > 50
]

clean_df.reset_index(drop=True, inplace=True)

print("Final Shape:", clean_df.shape)

clean_df.head()

Final Shape: (19692, 7)

,ACN,Date,Primary Problem,Contributing Factors / Situations,Result,Synopsis,full_narrative
0,2068164,202401,Human Factors,Procedure; Human Factors,Flight Crew Rejected Takeoff; Flight Crew Took...,DA-7X flight crew rejected a takeoff due to an...,Was told to line up and wait runway XXR at int...
1,2068412,202401,Human Factors,Human Factors; Procedure,General None Reported / Taken,Ground observer reported a critical ground con...,A large corporate aircraft taxied with in 5-8 ...
2,2068417,202401,ATC Equipment / Nav Facility / Buildings,ATC Equipment / Nav Facility / Buildings; Airc...,Flight Crew Overcame Equipment Problem,Air carrier pilot reported GPS spoofing at cru...,GPS Spoofing. Enroute today from ZZZ to SOF; w...
3,2068537,202401,Human Factors,Human Factors; Procedure,Flight Crew Took Evasive Action,General aviation Instructor reported a near mi...,Practicing simulated arcs with instrument stud...
4,2068539,202401,Procedure,Chart Or Publication; Procedure; Airspace Stru...,Flight Crew Requested ATC Assistance / Clarifi...,Experimental aircraft pilot operating in ZMA a...,I was enroute southeast bound on T208 VFR; in ...

In [6]:
clean_df.to_csv(
    "asrs_clean.csv",
    index=False
)

print("Dataset saved!")

Dataset saved!